# Generated by Django 4.1.7 on 2023-06-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grademod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgroup',
            name='Group_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='Group_ID',
            field=models.ForeignKey(db_column='Group_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schoolList', to='grademod.schoolgroup'),
        ),
    ]
