# Generated by Django 4.1.7 on 2023-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grademod', '0002_alter_schoolgroup_group_id_alter_schooltype_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgroup',
            name='Group_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
